server:
  port: 8013
  
spring:
  cloud:
    consul:
      discovery:
        instanceId: purchase-service
        health-check-interval: 15s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
